//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelOfFortune.Properties
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        /// <summary>
        /// Defines the resourceMan.
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Defines the resourceCulture.
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Resources"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        /// Gets the ResourceManager
        /// Returns the cached ResourceManager instance used by this class..
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WheelOfFortune.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the Culture
        /// Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class..
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the puzzles
        /// Looks up a localized string similar to Njeri Thande,
        ///Adela Darmansyah,
        ///Alejandro Ficachi,
        ///Alexandra Duboy,
        ///Andrew Fowose,
        ///Cecilia Choi,
        ///Dustin Morris,
        ///Eddie Harmon,
        ///Emirhan Kaplan,
        ///Evgeniya Chernaya,
        ///Gulzat Karimova,
        ///Hamida Shaik,
        ///Ibrahem Adem,
        ///Jennifer Chen,
        ///John Tieu,
        ///Joseph Yang,
        ///Khushboo Thakur,
        ///Kristi Gordon,
        ///Kristina Tae,
        ///Leo Kukharau,
        ///Lune Campos,
        ///Marella Cruz,
        ///Margarita Kalacheva,
        ///Maria Wissler,
        ///Mariia Stashuk,
        ///Mark Calvelo,
        ///Mark Stenerson,
        ///Marlene Guzman,
        ///Marlon Decosta,
        ///Marlon Hernandez,
        ///Mathieu Lefebvre,        /// [rest of string was truncated]&quot;;..
        /// </summary>
        internal static string puzzles
        {
            get
            {
                return ResourceManager.GetString("puzzles", resourceCulture);
            }
        }
    }
}
